// <auto-generated />
using AggregationApp.Application.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace AggregationApp.Application.Migrations
{
    [DbContext(typeof(AggregationDbContext))]
    [Migration("20230610125224_initial")]
    partial class initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.16")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("AggregationApp.Application.Models.AggregatedData", b =>
                {
                    b.Property<string>("Region")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("region")
                        .HasColumnOrder(0);

                    b.Property<decimal>("PMinus")
                        .HasColumnType("numeric")
                        .HasColumnName("pminus");

                    b.Property<decimal>("PPlus")
                        .HasColumnType("numeric")
                        .HasColumnName("pplus")
                        .HasColumnOrder(1);

                    b.HasKey("Region")
                        .HasName("pk_aggregated_data");

                    b.ToTable("aggregated_data");
                });
#pragma warning restore 612, 618
        }
    }
}
